language: node_js
node_js:
  - "0.10"
env:
  - HEADLESS=true SELENIUM_VERSION=2.39.0
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: "npm install"
cache:
  directories:
    - node_modules
