language: node_js
node_js:
  - "0.10"
before_install:
  #- "find / -maxdepth 5"
  - "sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome"
  # - "Xvfb :99 > /dev/null &"
install: "npm install"
cache:
  directories:
    - node_modules
